// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr8sJONDZ5-jKqvtthlpX1-JBQiDBDfG8',
    appId: '1:894261280685:android:00ec11bf10e78ab6bfeb24',
    messagingSenderId: '894261280685',
    projectId: 'auth-and-notification',
    storageBucket: 'auth-and-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS-7XzAYgcxVidh25tYHxPHeR6LF1fEG8',
    appId: '1:894261280685:ios:363922992368ae7ebfeb24',
    messagingSenderId: '894261280685',
    projectId: 'auth-and-notification',
    storageBucket: 'auth-and-notification.firebasestorage.app',
    androidClientId: '894261280685-pk562uaic5fjecjd3eprlkb79uks2eud.apps.googleusercontent.com',
    iosClientId: '894261280685-6em5kh5vvaonjlna7nm8gb6e375j0t55.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenticationAndNotification',
  );

}